### ISSUE TITLE
增加一个复制代码的按钮

### ISSUE THREAD

**Issue by fancymax** [MartinLau7/ColorCalculater#1]
[NSColor colorWithCalibratedRed:0.375817 green:0.788235 blue:0.254485 alpha:1.0]
产生代码的这里，可以增加一个复制的按钮，这样用起来更方便。

**Comment by fancymax** [comment]
有个直接写进剪切板的功能，那就不需要这个了

**Comment by MartinLau7** [comment]
这个之前有 后面就直接写入剪切板了
